### PR TITLE
Add logos for main projects

### PR DESCRIPTION
**Pull request by relu91**
As discussed during the last internal meeting this PR centralizes the collection of logos for our sub-projects. Please review if the naming style, folder structure, and design are what you were expecting.

For reference, [here](https://github.com/eclipse-thingweb/thingweb/wiki/Committer-Meeting-%E2%80%90-22.12.2023#decisions-and-resolutions) is the agenda with the action point and an early version of the logos.

### CODE REVIEW

**Comment by egekorkan** [comment]
I am not sure if it is due to my browser but I see a different font (see screenshot below) that is probably time roman since that is what Inkscape uses as a fallback when the font is unknown. Opening in Inkscape seems better but the agenda screenshot is still different. There it is more bold? 

Browser:

image

Inkscape:

image

**Comment by relu91** [comment]
Oh yeah, I didn't convert the text element to path. We'll lose the ability to easily change the text, but it is the only way to make it work in different envs.

**Review by danielpeintner — CHANGES_REQUESTED** [review]
I am pretty sure that the 2 files for for `project-name` use the wrong font .... exactly for "project-name".
They look different (not bold, style, font, something .. ) compared to all the others ...

Apart from that it looks good, thanks!

**Comment by danielpeintner** [comment]
> > I am pretty sure that the 2 files for for project-name use the wrong font .... exactly for "project-name".
> > They look different (not bold, style, font, something .. ) compared to all the others ...
> 
> Sorry, I forgot to report what Ege and I discussed on Telegram. We decided that the `template.svg` should keep the SVG text element so that it is easy to edit if we want to introduce a new logo. Therefore, if you don't have [Josefin Sans](https://github.com/eclipse-thingweb/website/blob/master/misc/designcrowd/fonts.zip) installed in your system you won't see them displayed correctly. Can you try installing the font and see if they look fine?

I just checked the "online"... version

image

**Comment by relu91** [comment]
Same problem, if you have the font installed they should be displayed like the following:
image

However, those two files should never be used as images on websites. They are just our template for creating new logos.

**Comment by danielpeintner** [comment]
I don't want to block this PR. I just think there is something broken since (as showed in https://github.com/eclipse-thingweb/thingweb/pull/4#issuecomment-1891694704) there is a difference.. I use the same machine/browser and the font looks different comparing "test-things" vs "project-name"

**Comment by relu91** [comment]
What I'm saying is that what you are seeing is the expected behavior. "test-things" looks correct because it does not use the text element but it has been converted to a path.

**Comment by danielpeintner** [comment]
> What I'm saying is that what you are seeing is the expected behavior. "test-things" looks correct because it does not use the text element but it has been converted to a path.

I see now what you are trying to explain 🙈

**Review by danielpeintner — APPROVED** [review]

**Comment by relu91** [comment]
> > What I'm saying is that what you are seeing is the expected behavior. "test-things" looks correct because it does not use the text element but it has been converted to a path.
> 
> I see now what you are trying to explain 🙈

ehehehe I did my best trying to explain but it was not easy! 😅

**Review by egekorkan — APPROVED** [review]

**Comment by egekorkan** [comment]
@relu91 I guess nothing more is planned right? We can merge it I think

**Pull request merged**
